### DISCUSSION TITLE
Problem with buttons

### DISCUSSION THREAD

**Discussion by vort7u** [orestbida/cookieconsent#204] [General]
Hi, I added the code before the `</body>` and following the guide but I have this problem:

![Immagine 2022-01-18 135710](https://user-images.githubusercontent.com/1554203/149944196-751d77dd-5469-42ab-9c8d-b4b8f50853b3.png)
![Immagine 2022-01-18 135727](https://user-images.githubusercontent.com/1554203/149944203-dc7487b4-63b1-400c-aa3c-40ee392b4de4.png)

I have not made any changes to the css, the site is based on [SMF](https://www.simplemachines.org)

Thanks

**Comment by orestbida** [comment]
Hi @mastum,

this is caused by the following css rule set by your website:
```css
input, button, select {
    padding: 0 0.4em;
    height: 2em;
    line-height: 2em;
}
```

you should be able to fix it with this:
```css
.cc_div *{
    height: auto;
}
```
