### DISCUSSION TITLE
Change style Reject all button in configuration page

### DISCUSSION THREAD

**Discussion by uralulas** [orestbida/cookieconsent#573] [General]
How I can change the class for changing the style of the Reject all button in the configuration popup page.
![image](https://github.com/orestbida/cookieconsent/assets/46848447/ca0b5b92-a4dd-478f-ba1e-21cd9d2311f4)

**Comment by orestbida** [comment]
@uralulas, you need custom css to target a single button:

```css
#cc-main .pm__btn[data-role="necessary"] {
    --cc-btn-primary-bg: red;
   
    /*
    --cc-btn-primary-border-color: red;
    --cc-btn-primary-color: #fff;
    --cc-btn-primary-hover-bg: #bbbbbb;
    --cc-btn-primary-hover-border-color: #cdcdcd;
    --cc-btn-primary-hover-color: red;
    */
}
```
