### ISSUE TITLE
Color of buttons from a legal perspective

### ISSUE THREAD

**Issue by tillsanders** [orestbida/cookieconsent#135]
I'm no legal expert, I'm just reading articles and try to understand the situation. On 15th September 2020, the state court Rostock issued a judgement (Az. 3 O 762/19) in a case where the owner of a website had implemented two dark patterns to nudge the visitors into accepting all cookies. 1) unnecessary cookies were pre-selected and 2) the 'accept all' button was green and well visible, while the 'deny all' button was light grey with white font color. Based on this decision, I have read several [articles](https://www.heuking.de/de/news-events/newsletter-fachbeitraege/artikel/aktuelle-handlungsempfehlungen-zur-ausgestaltung-von-cookie-bannern.html) (German, sry...) now that advise to make both buttons visually identical. It is probably okay to style them a little (!) differently, but to be on the safe side (and also – fair to the users) they should be visually equal. 

Obviously, this can be easily addressed using a little CSS. But I was wondering if this shouldn't be the default and the current implementation an exception.

**Comment by tillsanders** [comment]
For anyone finding this issue, let me save you some time by showing you a CSS solution ;)

```css
#cc--main {
  --cc-btn-primary-bg: #111;
  --cc-btn-primary-text: #fff;
  --cc-btn-primary-hover-bg: #222;
  --cc-btn-secondary-bg: #111;
  --cc-btn-secondary-text: #fff;
  --cc-btn-secondary-hover-bg: #222;
}
```
