### ISSUE TITLE
Cookie tables are not displaying correctly.

### ISSUE THREAD

**Issue by lamtonylam** [orestbida/cookieconsent#141]
![image](https://user-images.githubusercontent.com/63186670/145691674-dc63ee56-1267-4c37-aeff-eda8ab9df290.png)

Problem only appears when my site is using light theme.

Here is my repo 
[https://github.com/lamtonylam/opkh/tree/test_cookie_table](https://github.com/lamtonylam/opkh/tree/test_cookie_table)

**Comment by orestbida** [comment]
Technically speaking this isn't a bug from the cookieconsent side. It is something specific to your website and seems to be caused by the following css rules — as they apply to all tables:

![scr](https://user-images.githubusercontent.com/34487268/145692539-ac460bfb-2159-4f9a-a338-8edd123c6fa6.PNG)

You should be able to fix it with this:
```css
#cc_div td{
    background: none;
}
```

With that being said, I will add the rule below — in the next release — to avoid future cases like yours.
```css
#cc_div table,
#cc_div th,
#cc_div tr,
#cc_div td{
    background: none;
}
```
