### ISSUE TITLE
Changing the style of the bar layout similar to a popular one

### ISSUE THREAD

**Issue by wzol** [orestbida/cookieconsent#185]
This is the bar layout for desktop what I'm looking for:
![cc0](https://user-images.githubusercontent.com/11561358/148332188-8a31e58f-89e0-4f19-b82b-9cbee41892cb.jpg)

It seems this is a familiar format of a consent dialog, also works better with longer texts:
- almost full width content
- buttons on the right side (they are closer to the scrollbar)

Can I use some CSS to achieve this? I tried some, but without any luck.

**Comment by tillsanders** [comment]
I'm sure you can achieve this using CSS. I haven't tried though, I'm just here for a quick comment on the UX: the lines in your screenshot are too long to be read comfortably. As a rule of thumb you'd want to be around 70 - 80 characters per line. If you feel that makes your text too long (which is obviously also a problem) you can use margins between paragraphs to provide visual anchors for readers. Or you can highlight some words in a bold font. What can also work well is to set the last paragraph to a smaller font size, given it contains less relevant information.

I hope you find a solution that serves you well ☺️

**Comment by wzol** [comment]
Thanks for your reply and you are absolutely right about the readability part - but I think that won't be a big issue if we think about how many users actually read that, also this layout covers much less of the real content. I'm trying to find a golden middle way :)

In CSS I'm having the most trouble aligning the buttons properly, just can't get it right. :/

**Comment by tillsanders** [comment]
I tried something like this, though the selectors probably should be improved. Also colors are missing, obviously:

```css
#cm {
	max-width: 80em;
}

.c-inr {
	display: flex;
	align-items: flex-start;
}

.cc_div #cm #c-bns {
	display: block;
}

.cc_div #c-bns .c-bn {
	float: none;
	width: 100%;
}

#c-bns button + button {
	margin-top: 1em;
	margin-left: 0;
}
```
