### ISSUE TITLE
CSS reset disables strong and emphasis

### ISSUE THREAD

**Issue by n3t** [orestbida/cookieconsent#222]
Hi, 

I found another small issue with CSS reset rules, using `strong` and `em` elements result in unfromatted text.
This piece of code should solve it:
```
.cc_div strong {
  font-weight: bold;
}
.cc_div strong:hover {
  font-weight: bold;
}
.cc_div em {
  font-style: italic;
}
.cc_div em:hover {
  font-style: italic;
}
```
BTW, do you plan some less or Sass?

**Comment by orestbida** [comment]
Css reset rules apply to all elements inside the modals. 

If you don't care about ie, you could use something like this:
```css
.cc_div ul,
.cc_div ol,
.cc_div li,  
.cc_div u, 
.cc_div i, 
.cc_div em, 
.cc_div b{
    all: revert!important;
}
```

It would be nice to switch to either less or sass in the future, but it will have to wait for now since there are way higher priority features to implement.
