### ISSUE TITLE
Embedded YouTube video

### ISSUE THREAD

**Issue by bboerendans** [orestbida/cookieconsent#234]
I'm using an embedded YouTube video via iframe tag to have a video played as a background on my homepage. Any idea how to get this compliant with cookie consent? All the online testing website for cookie compliance are yelling about that one

Besides that, thanks for all the work, working really well :D

**Comment by ozgurg** [comment]
I think it might be better if you open this issue here: https://github.com/orestbida/iframemanager

**Comment by bboerendans** [comment]
Super, will have a look at iframemanager. 
Those limitations are fine for me, since i'm using it already that way :D 

Thanks!

**Comment by orestbida** [comment]
@bboerendans,

I took a bit of my time to create a demo example with iframemanager's video set as background.

If the analytics category is accepted => autoplay video.

I hid the notice and controls for the iframe, since it will be used as a background video:
```css
/* Hide iframe manager controls (since we want the video to start only if analytics category is accepted) */
  #fullscreen-bg .c-nt,
  #fullscreen-bg .c-bg::before {
      display: none;
}
```

Final result: https://mkp3dg.csb.app/
Code: https://codesandbox.io/s/cookieconsent-iframemanager-fullscreen-mkp3dg?file=/index.html

You can ignore the assets folder, package.json and also sandbox.config.json.
