### ISSUE TITLE
Text out of view on mobile (iphone5)

### ISSUE THREAD

**Issue by gh4l3b** [orestbida/cookieconsent#285]
Hi,

I have an issue the cookie banner is out of view, I only test it on iphone5 so I would expect the same problem on iphone4. Long text is required recently by law in some of the EU countries. 
Please can you help me fix this issue thanks
![Screenshot from 2022-04-03 14-45-14](https://user-images.githubusercontent.com/97788614/161428734-3654af84-0460-4c0d-8abd-35e31d62ab7e.png)

**Comment by orestbida** [comment]
Hi @gh4l3b,

you should be able to fix this with a little css:
```css
#c-txt{
    overflow: auto!important;
    max-height: 40vh!important;
}
```

You can change the `40vh` value to something else, based on your preference.

This fix will be included in the future `v3` version.
