### ISSUE TITLE
[Feat]: Contrast ratio issue for buttons to improve accessibility

### ISSUE THREAD

**Issue by sovetski** [orestbida/cookieconsent#725]
### Description

Hi,

Current version of the library have a small issue with button color contrast

Light theme colors score:
![image](https://github.com/user-attachments/assets/50c73fdb-7a68-45d1-b1a3-f168776f84b5)

Dark theme colors score:
![image](https://github.com/user-attachments/assets/a008e1d2-3f37-4e8a-9c0e-e56ae713b7ff)

To improve the accessibility score, the contrast ratio must be at least 7:1

### Proposed solution

To improve it, I suggest these colors:

```css
#cc-main {
	--cc-btn-secondary-bg: #414e55;
	--cc-btn-secondary-color: #fff;
}

.cc--darkmode #cc-main {
	--cc-btn-secondary-bg: #96b6cd;
	--cc-btn-secondary-color: #1e1e1e;
}
```

With these changes:

Light mode before:
![image](https://github.com/user-attachments/assets/163511c4-eb32-4503-80f2-a082b3dc2b8a)

Light mode after:
![image](https://github.com/user-attachments/assets/84efcabc-de2b-4833-aa6b-bc95ae70414d)

Light mode new score:
![image](https://github.com/user-attachments/assets/19f5ab05-8b08-4ea1-93f8-2f82049fe258)

Dark mode before:
![image](https://github.com/user-attachments/assets/753b6587-caf2-45ed-80e3-b2d0dfc3ad4b)

Dark mode after:
![image](https://github.com/user-attachments/assets/bfb7822b-b227-4753-b9c4-fd5a9d9c4e50)

Dark mode new score:
![image](https://github.com/user-attachments/assets/978d0bd0-bbf7-4ece-bbc2-855c02833265)
