### ISSUE TITLE
Order of the buttons

### ISSUE THREAD

**Issue by jnachtigal1** [orestbida/cookieconsent#83]
Please advise - I can't figure out how to change the order of the buttons. Acceptance on the right, setting on the left. Thanks.

**Comment by orestbida** [comment]
Hi @jnachtigal1,

unfortunately there is no option to swap buttons, but you can still achieve this with a little bit of css:

```css
#c-bns #c-s-bn {
    float: none;
}

#c-bns #c-p-bn{
    float: right;
}
```
